export const step2Types = {
    SET_DEVICE_INFORMATION: "SET_DEVICE_INFORMATION",
    CLEAR_REDUCERS: "CLEAR_REDUCERS_STEP2"
}

export const step3Types = {
    SET_NETWORKS_LIST: "SET_NETWORKS_LIST",
    SET_CONNECTED: "SET_CONNECTED",
    CLEAR_REDUCERS: "CLEAR_REDUCERS_STEP3"
}

export const findDevicesTypes = {
    SET_DEVICES_LIST: "SET_DEVICES_LIST",
    CLEAR_REDUCERS: "CLEAR_REDUCERS_FIND_DEVICES"
}

export const checkAddressesTypes = {
    SET_WESOCKET_OBJECT: "SET_WESOCKET_OBJECT",
    SET_WESOCKET_RESPONSE: "SET_WESOCKET_RESPONSE",
    CLEAR_REDUCERS: "CLEAR_REDUCERS_SETUP_MODBUS"
}

export const assignTagsTypes = {
    SET_TAGS_OBJECT: "SET_TAGS_OBJECT",
    CLEAR_REDUCERS: "CLEAR_REDUCERS_ASSIGN_TAGS"
}

export const serverSideSettingTypes = {
    SET_DEVICE_TOKEN: "SET_DEVICE_TOKEN",
    CLEAR_REDUCERS: "CLEAR_REDUCERS_SERVER_SIDE_SETTING"
}