export const routeNames = {
    home: "/",
    modbus: "/modbus/select-operation",
    connection: "/connection/step1",
    connection2: "/connection/step2",
    connection3: "/connection/step3",
    connection4: "/connection/step4/:network",
    checkMbAddressesSerial: "/modbus/check-serial",
    checkMbAddressesTcp: "/modbus/check-tcp",
    findDevices: "/config/find-devices/:toPath",
    assignTags: "/modbus/assignTags",
    configSelection: "/config/config-selection",
    configureServer: "/config/server",
    configureModbus: "/config/modbus",
}